---
- name: Apply SeLinux virtualization booleans, if SELinux is enabled.
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('no') }}"
  with_items: "{{ libvirt_selinux_booleans }}"
  when: ansible_selinux.status == "enabled"

- name: Enable the libvirt NSS module.
  lineinfile:
    path: /etc/nsswitch.conf
    backrefs: true
    regexp: '^(hosts:\s*.*)(?<!libvirt)$'
    line: '\1 libvirt'
  when: libvirt_access_vms_using_hostnames | bool

- name: Allow members of the libvirt group to have password-less access to the RW daemon.
  block:
    - name: Ensure the libvirt group exists.
      group:
        name: libvirt
        state: present

    - name: Add user(s) to the libvirt group.
      user:
        name: "{{ item }}"
        groups: libvirt
        append: true
      with_items: "{{ libvirt_users_in_libvirt_group }}"
  when: libvirt_users_in_libvirt_group is defined
