---
- name: RedHat | Install required packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present

- name: RedHat | Install virt-manager
  ansible.builtin.yum:
    name: virt-manager
    state: present
  when: libvirt_install_virt_manager | bool

- name: RedHat | Install edk2-ovmf for UEFI VMs
  ansible.builtin.yum:
    name: "{{ ovmf_package }}"
    state: present
  when: libvirt_uefi_vm_support | bool
