---
- name: Archlinux | Ensure system is up-to-date
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Archlinux | Install required packages.
  ansible.builtin.shell: "yes | pacman -S {{ item }}"
  args:
    executable: /bin/bash
  changed_when: false
  with_items:
    - "{{ packages }}"

- name: Archlinux | Install virt-manager
  community.general.pacman:
    name: virt-manager
    state: present
  when: libvirt_install_virt_manager | bool

- name: Archlinux | Install edk2-ovmf for UEFI VMs
  community.general.pacman:
    name: edk2-ovmf
    state: present
  when: libvirt_uefi_vm_support | bool
