---
- name: Ensure system is up-to-date.
  community.general.pacman:
    update_cache: true
    upgrade: true
    
- name: Install required packages.
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Install virt-manager.
  community.general.pacman:
    name: virt-manager
    state: present
  when: libvirt_install_virt_manager | bool

- name: Install virt-manager.
  community.general.pacman:
    name: edk2-ovmf
    state: present
  when: libvirt_uefi_vm_support | bool
