---
- name: Set distribution family specific variables.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- name: Install required packages.
  include_tasks: "installation-{{ ansible_os_family }}.yml"

- name: Configuration.
  include_tasks: configuration.yml

- name: Ensure the libvirt service is started and enabled on boot.
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true
